// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5arLBdbf_0iZdxzZZ2o6sutV-ninp58Y',
    appId: '1:95077470122:web:1b8b9ed159cbd38289e5d3',
    messagingSenderId: '95077470122',
    projectId: 'audiologoformulario',
    authDomain: 'audiologoformulario.firebaseapp.com',
    storageBucket: 'audiologoformulario.appspot.com',
    measurementId: 'G-XJSFYNV1QG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHkLmasUGJkBua11d2lyuPXky7qsdrHtg',
    appId: '1:95077470122:android:a370e1b88ee89f9589e5d3',
    messagingSenderId: '95077470122',
    projectId: 'audiologoformulario',
    storageBucket: 'audiologoformulario.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7_NvbAUO3Fl8Y3gVP1D60L0jWbJmXPco',
    appId: '1:95077470122:ios:8908b61bf2f5cee889e5d3',
    messagingSenderId: '95077470122',
    projectId: 'audiologoformulario',
    storageBucket: 'audiologoformulario.appspot.com',
    iosBundleId: 'com.example.formAudiologo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7_NvbAUO3Fl8Y3gVP1D60L0jWbJmXPco',
    appId: '1:95077470122:ios:8908b61bf2f5cee889e5d3',
    messagingSenderId: '95077470122',
    projectId: 'audiologoformulario',
    storageBucket: 'audiologoformulario.appspot.com',
    iosBundleId: 'com.example.formAudiologo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5arLBdbf_0iZdxzZZ2o6sutV-ninp58Y',
    appId: '1:95077470122:web:ff249dc4a871090089e5d3',
    messagingSenderId: '95077470122',
    projectId: 'audiologoformulario',
    authDomain: 'audiologoformulario.firebaseapp.com',
    storageBucket: 'audiologoformulario.appspot.com',
    measurementId: 'G-6G9GQW7KEE',
  );
}
